Add xk6-nostr
grafana/k6-docs pull request #1404
Opened 2023-11-08 11:30 UTC by akiomik

Hi, I created an extension to interact with Nostr relays.
This extension is useful for relay load testing.

- https://github.com/akiomik/xk6-nostr

NOTE: Nostr is a protocol that mainly designed for distributed social media. Nostr uses websockets for communication between clients and servers (relays).

ref:

- http://nostr.com
- https://en.wikipedia.org/wiki/Nostr

2023-11-13 20:33 UTC, heitortsergent commented
@akiomik thanks for creating this extension! I'll get someone on the team to take a look at it. 🙇

2023-12-08 19:06 UTC, javaducky requested changes
Just one minor change for the author url.

2023-12-08 19:06 UTC, javaducky commented on src/data/doc-extensions/extensions.json
> +        "url": "https://github.com/nostr"
```suggestion
        "url": "https://github.com/akiomik"
```

2023-12-08 19:22 UTC, akiomik commented on src/data/doc-extensions/extensions.json
> +        "url": "https://github.com/nostr"
Thanks👍

2023-12-08 19:37 UTC, javaducky approved these changes
LGTM! Thank you!

2023-12-08 19:37 UTC, merged