docs: update running-browser-tests.md
grafana/k6-docs pull request #1634
Opened 2024-06-25 20:02 UTC by MoKhajavi75

## What?

Use more general term for new Macbooks.

## Checklist

- [x] I have used a meaningful title for the PR.
- [x] I have described the changes I've made in the "What?" section above.
- [x] I have performed a self-review of my changes.
- [x] I have run the `npm start` command locally and verified that the changes look good.
- [ ] I have made my changes in the `docs/sources/next` folder of the documentation.
- [x] I have reflected my changes in the `docs/sources/v{most_recent_release}` folder of the documentation.
- [ ] I have reflected my changes in the relevant folders of the two previous k6 versions of the documentation (if still applicable to previous versions).

## Related PR(s)/Issue(s)

None

2024-06-25 20:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-docs?pullRequest=1634) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-docs?pullRequest=1634) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-docs?pullRequest=1634) it.</sub>

2024-06-25 20:36 UTC, heitortsergent requested changes
@MoKhajavi75 thanks for your contribution! I made a small change since we can have other Mac computers with Apple Silicon besides MacBooks.

2024-06-25 20:36 UTC, heitortsergent commented on docs/sources/next/using-k6-browser/running-browser-tests.md
> +1. Optional step: running browser tests in Docker on Macbooks with Apple Silicon:
```suggestion
1. Optional step: running browser tests in Docker on Mac computers with Apple Silicon:
```

2024-06-25 20:36 UTC, heitortsergent commented on docs/sources/v0.49.x/using-k6-browser/running-browser-tests.md
> +1. Optional step: running browser tests in Docker on Macbooks with Apple Silicon:
```suggestion
1. Optional step: running browser tests in Docker on Mac computers with Apple Silicon:
```

2024-06-25 20:36 UTC, heitortsergent commented on docs/sources/v0.50.x/using-k6-browser/running-browser-tests.md
> +1. Optional step: running browser tests in Docker on Macbooks with Apple Silicon:
```suggestion
1. Optional step: running browser tests in Docker on Mac computers with Apple Silicon:
```

2024-06-25 20:36 UTC, heitortsergent commented on docs/sources/v0.51.x/using-k6-browser/running-browser-tests.md
> +1. Optional step: running browser tests in Docker on Macbooks with Apple Silicon:
```suggestion
1. Optional step: running browser tests in Docker on Mac computers with Apple Silicon:
```

2024-06-25 20:36 UTC, heitortsergent commented on docs/sources/v0.52.x/using-k6-browser/running-browser-tests.md
> +1. Optional step: running browser tests in Docker on Macbooks with Apple Silicon:
```suggestion
1. Optional step: running browser tests in Docker on Mac computers with Apple Silicon:
```

2024-06-26 08:37 UTC, MoKhajavi75 commented
Totally missed that point 😁 
Thanks & Done @heitortsergent

2024-06-27 15:46 UTC, heitortsergent approved these changes
LGTM! 🚀  Thanks for your contribution! 🙇

2024-06-27 16:00 UTC, merged