JS API for execution.test.abort
grafana/k6-docs pull request #559
Opened 2022-01-20 14:57 UTC by codebien

Docs for `test.abort()` new feature

2022-01-21 09:34 UTC, imiric requested changes

2022-01-21 09:34 UTC, imiric commented on src/data/markdown/docs/02 javascript api/06 k6-execution.md
> +| abort | | It immediately aborts a k6 load test run with the exit code `108`. Aborting a test is fully supported in `k6 cloud`, preserving the same user experience for both local and cloud users. |
I'm wondering if "field" is the right column name... "Property" would be more accurate. Same goes for the other sections. It's unrelated to this PR, but we might as well change it here if you agree.

And perhaps the value of Type here could be "function"?

2022-01-21 10:12 UTC, imiric approved these changes
Great! Thanks a lot for picking this up! :smile:

2022-01-21 10:48 UTC, oleiade approved these changes
Nickel Chrome 👍🏻 Cheers for that 🦖

2022-01-24 06:33 UTC, na-- approved these changes

2022-01-24 08:46 UTC, merged

2022-01-24 12:47 UTC, ppcano commented
@codebien @na-- 

Because the default behavior of k6 is `same user experience for both local and cloud users`,  I suggest removing:

`Aborting a test is fully supported in k6 cloud, preserving the same user experience for both local and cloud users.`

And, only provide the details on the exceptions.