Fix the default value for setup/teardown timeouts
grafana/k6-docs pull request #628
Opened 2022-04-20 15:33 UTC by codebien

I updated the setup/teardown timeouts' default values with the real value used in the code.

https://github.com/grafana/k6/blob/ff198a857003152e0dad2a834d88adb596427579/cmd/options.go#L126-L129

2022-04-20 15:52 UTC, olegbespalov commented on src/data/markdown/translated-guides/en/02 Using k6/05 Options.md
> +| `K6_SETUP_TIMEOUT` | N/A | `setupTimeout`     | `"60s"` |
por favor también :) 

https://github.com/grafana/k6-docs/blob/main/src/data/markdown/translated-guides/es/02%20Using%20k6/05%20Options.md#teardown-timeout

2022-04-20 15:53 UTC, olegbespalov requested changes
We have to fix a Spanish version too :smile:

2022-04-21 07:56 UTC, ppcano commented
Can this be merged now or should be after the next release?

2022-04-21 08:18 UTC, codebien commented
>Can this be merged now or should be after the next release?

@ppcano We can merge it now, this value had been defined a long time ago so we already have released versions with it.

2022-04-21 08:22 UTC, merged