Resections and rewords create-extension docs
grafana/k6-docs pull request #756
Opened 2022-08-04 12:37 UTC by MattDodsonEnglish

The "Create" docs mentioned that it's necessary to know the Go-Js bridge,
but this info is buried in the middle of the "create JS extension" tutorial.

Splitting this topic into a new "Explanation" section makes the
information easier to find, more general (it applies to output
extensions too), and it opens up a designated space for future "deep-dive"
topics.

As I extracted it, I took the time to make the tutorial a little shorter
and have a more evidently procedural format.

2022-08-04 15:16 UTC, javaducky requested changes
All seems good to me other than a couple of minor issues noted.

2022-08-04 15:16 UTC, javaducky commented on src/data/markdown/docs/07 extensions/01 Getting started/04 Create/01 JavaScript Extensions.md
> +	console.log(`${compare.isGreater(1, 3)}, ${compare.comparison_result}`);
For some reason, the indentation of the code is lost when rendered on the page.

2022-08-04 15:16 UTC, javaducky commented on src/data/markdown/docs/07 extensions/01 Getting started/04 Create/02 Output Extensions.md
> +`xk6-output-logger` is the Go module name passed to `go mod init`>
You have a trailing `>` character...presumably, this should have been a `.`.

2022-08-04 17:30 UTC, MattDodsonEnglish commented on src/data/markdown/docs/07 extensions/01 Getting started/04 Create/02 Output Extensions.md
> +`xk6-output-logger` is the Go module name passed to `go mod init`>
```suggestion
`xk6-output-logger` is the Go module name passed to `go mod init`
```

2022-08-10 13:22 UTC, javaducky reviewed
Still seeing some mix of 2- and 4-space indention within a single example. Ideally, the JavaScript examples are 2-space (which it appears they all are), and that the Go examples are using 4-space indention, seeing some mixes as in the following:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/944496/183911791-836ce6ff-679f-4dd3-8490-73aaeffd1e77.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/944496/183919768-a984e2a5-5619-47c5-9ac7-04dafa85b40d.png">

2022-08-10 20:59 UTC, javaducky requested changes

2022-08-10 20:59 UTC, javaducky commented on src/data/markdown/docs/07 extensions/01 Getting started/04 Create/02 Output Extensions.md
> +          for _, sample := range samples {
```suggestion
      for _, sample := range samples {
```

2022-08-10 21:02 UTC, javaducky approved these changes

2022-08-10 21:33 UTC, merged