[feat] Update Audit Trail docs
grafana/k6-docs pull request #819
Opened 2022-10-04 08:42 UTC by 2Steaks

- Describe new filtering functionality
- Update example image with highlighted areas on interest

2022-10-04 23:38 UTC, MattDodsonEnglish requested changes
I reworked it to emphasize action and to not use color as the main way to distinguish features. Otherwise seems good to me.

2022-10-04 23:38 UTC, MattDodsonEnglish commented on src/data/markdown/docs/03 cloud/03 Manage/06 Audit Trail.md
> +- Highlighted in orange are columns that can sort the results.
```suggestion
## Viewing Results

- To view results within a specified time frame, use the **period** filter (highlighted in green).
- To change how results are sorted, use the columns (highlighted in orange).
```

2022-10-05 08:17 UTC, 2Steaks commented on src/data/markdown/docs/03 cloud/03 Manage/06 Audit Trail.md
> +- Highlighted in orange are columns that can sort the results.
Thank you! 🥳

2022-10-05 12:32 UTC, MattDodsonEnglish approved these changes

2022-10-05 12:32 UTC, merged