Life-cycle, rename functions, justify design
grafana/k6-docs pull request #873
Opened 2022-11-08 14:27 UTC by MattDodsonEnglish

Fixes #845

2022-11-08 19:50 UTC, MattDodsonEnglish commented
> Sometimes, it is used life cycle instead of lifecycle.

Fixed. I was trying to be cute and use "life cycle" as a noun and "lifecycle" as an adjective, but it's too complicated. Chose "lifecycle", following React's example. [^1]

> lifecycle and stages seems the same but the content does not clearly notice the relationship or difference.

I think a lifecycle goes through different stages. The word "stage" is all over the wikipedia entry for "life cycle". But hopefully the first sentence makes it a little clearer.

> Is the Design reasons for k6 stages section necessary?

Probably not. I was feeling cute, might delete later :-). 

[^1]: https://reactjs.org/docs/state-and-lifecycle.html

2022-11-09 03:43 UTC, ppcano requested changes
Requested removing the last section. The rest LGTM - 💯

2022-11-09 03:43 UTC, ppcano commented on src/data/markdown/translated-guides/en/02 Using k6/06 Test life cycle.md
> +## Design reasons for k6 stages
Remove this entire section and check if the content is necessary somewhere else

2022-11-09 03:43 UTC, ppcano commented on src/data/markdown/translated-guides/en/02 Using k6/06 Test life cycle.md
> +* Stabler, more meaningful test results.
1 - I think it can be removed as it is mentioned in the init code section.

2022-11-09 03:43 UTC, ppcano commented on src/data/markdown/translated-guides/en/02 Using k6/06 Test life cycle.md
> +* Portable scripts
`Portable scripts` can belong to https://k6.io/docs/misc/archive-command/

2022-11-09 03:43 UTC, ppcano commented on src/data/markdown/translated-guides/en/02 Using k6/06 Test life cycle.md
> +* Reusable functions
This section is about test modularization. It can be removed and will be mentioned on other sections when we expand more about this topic.

2022-11-09 09:29 UTC, ppcano approved these changes

2022-11-10 14:37 UTC, merged