xk6, Clarify output extensions
grafana/k6-docs pull request #924
Opened 2022-11-29 16:09 UTC by MattDodsonEnglish

2022-11-29 22:03 UTC, javaducky requested changes
Just a minor update.

2022-11-29 22:03 UTC, javaducky commented on src/data/markdown/docs/07 extensions/01 Get started/04 Create/02 Output Extensions.md
> +The `-out logger` argument tells k6 to use your custom output. The flag
```suggestion
The `--out logger` argument tells k6 to use your custom output. The flag
```

2022-11-29 22:09 UTC, javaducky commented
Also, wondering if we shouldn't change the phrasing of the 3rd bullet in https://mdr-ci.staging.k6.io/docs/refs/pull/924/merge/extensions/#extension-use-cases ?

2022-11-29 22:12 UTC, MattDodsonEnglish commented on src/data/markdown/docs/07 extensions/01 Get started/04 Create/02 Output Extensions.md
> +The `-out logger` argument tells k6 to use your custom output. The flag
:bow:

2022-11-29 22:19 UTC, MattDodsonEnglish commented
> Also, wondering if we shouldn't change the phrasing of the 3rd bullet in https://mdr-ci.staging.k6.io/docs/refs/pull/924/merge/extensions/#extension-use-cases ?

Good point, sorry I missed that one. What do you think of the text in https://github.com/grafana/k6-docs/pull/924/commits/42eefe6a8d5a88aeed25131168d44656ee57cf0a?

2022-11-30 12:52 UTC, javaducky approved these changes
LGTM!

2022-11-30 14:21 UTC, merged