disruptor, style edits
grafana/k6-docs pull request #950
Opened 2022-12-15 19:38 UTC by MattDodsonEnglish

imperative headings for tasks, shorter sentences, more list formatting, and so on.

2022-12-16 13:57 UTC, MattDodsonEnglish commented on src/data/markdown/docs/40 xk6-disruptor/03 Examples/01 Inject HTTP faults into Pod.md
> +The test uses the `delay` endpoint which, returns after the requested delay.
```suggestion
The test uses the `delay` endpoint, which returns after the requested delay.
```

2022-12-16 14:01 UTC, MattDodsonEnglish commented
@pablochacin  These edits are quite minor, and uncontroversial. But I wanted to flag you for a quick review just for move visibility.

2022-12-23 15:08 UTC, pablochacin requested changes
I like the changes. The texts is more fluid and terse. Only some minor changes.

2022-12-23 15:08 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/01 Get started/02 Requirements.md
>  You also need to ensure your test application is accessible from the machine where the tests run.
```suggestion
- Ensure your test application is accessible from the machine where the tests run.
```

2022-12-23 15:08 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/03 Examples/01 Inject HTTP faults into Pod.md
> +To run these tests, you need to deploy the `httpbin` application.
```suggestion
To run this test, you need to deploy the `httpbin` application.
```

2022-12-23 20:22 UTC, MattDodsonEnglish commented
@pablochacin , do you mind checking one last edit in commit [de76dff](https://github.com/grafana/k6-docs/pull/950/commits/de76dff9eea1a0e0e86d6faaba0d15b2a2cefa76).
 
- I bolded the titles of the requirements to make them easier scan.
- I made the final item a noun phrase, to keep the list parallelism.
- Moved the Kubernetes version info to the very top, since it's essential info. I also try to be cautious of using admonitions  because of the [banner blindness](https://en.wikipedia.org/wiki/Banner_blindness) phenomenon.

I also created a merge conflict somehow :facepalm: ―something that happened when I made the edit with the github UI?―but I'll figure that out later.

2023-01-16 08:48 UTC, pablochacin reviewed
@MattDodsonEnglish In general, I prefer the original phrasing. These changes are introducing some subtle changes in the meaning that I that I don't agree with. I understand you want to streamlined the text, but I think it is important to preserve relevant details. Sometimes less is not more but less.

2023-01-16 08:48 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/01 Get started/02 Requirements.md
> +- **A bundled k6 extension that includes the disruptor.**
@MattDodsonEnglish I find the term "a boundle k6 extension" confusing. Is that the way we are referring now to the custom k6 binaries with bundled extensions?

I think the original phrase was something like "a custom k6 binary that bundles the xk6-disruptor extension".

2023-01-16 08:48 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/01 Get started/02 Requirements.md
> +At this moment,
No at this moment. It is an extension. And it is intended for systems running kubernetes. And it requires kubernetes 1.23. I prefer the original phrasing.

2023-01-16 08:48 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/01 Get started/02 Requirements.md
> +- **A test application that is accessible from the machine where the tests run.**
I prefer the original phrasing.

2023-01-16 08:49 UTC, pablochacin commented on src/data/markdown/docs/40 xk6-disruptor/01 Get started/02 Requirements.md
> -`xk6-disruptor` requires the [grafana/xk6-disruptor-agent](https://github.com/grafana/xk6-disruptor/pkgs/container/xk6-disruptor-agent) image for injecting the [disruptor agent](/javascript-api/xk6-d
I think you are removing relevant details here. Why is this image needed? I prefer the original phrasing.

2023-03-15 10:06 UTC, pablochacin commented
Closing, as discussed with @MattDodsonEnglish, mostly due to changes in the wording are introducing subtle changes in the meaning.

2023-03-15 10:06 UTC, closed without merging